version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zayanmomin@gmail.com
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis